add osd-parition-del
unitedstack/gremlin pull request #27
Opened 2017-08-24 10:42 UTC by haoxiaoci

2017-08-24 11:11 UTC, hex2dec commented on roles/storage/tasks/recover_osd_partition.yml
> +   - name: Waiting 10 seconds to warm down
warn down？

2017-08-25 03:26 UTC, hex2dec requested changes
SGTM。整体思路很好，需要考虑权限问题，不能假设执行ansible 命令的用户为 root，我们一般推荐使用普通用户+sudo方式。

2017-08-25 04:09 UTC, haoxiaoci commented on roles/storage/tasks/recover_osd_partition.yml
> +   - name: Waiting 10 seconds to warm down
ha?

2017-08-25 05:41 UTC, hackerain commented
把commit合成一个吧

2017-08-25 05:51 UTC, hackerain reviewed
-1

2017-08-25 05:51 UTC, hackerain commented on roles/storage/tasks/del_osd_partition.yml
> +      - "{{ ceph_osd_disk.results }}"
加空格

2017-08-25 05:51 UTC, hackerain commented on playbooks/storage/osd/del_osd_partition.yml
> +
去掉空格

2017-08-25 05:51 UTC, hackerain commented on roles/storage/tasks/del_osd_partition.yml
> +  - shell: "df -h |grep ceph-{{ item }} |awk '{print $1}'|sed 's/[0-9]//g'"
给这个task加上name，说明做了什么工作。

2017-08-25 05:51 UTC, hackerain commented on roles/storage/tasks/del_osd_partition.yml
> +  - shell: "df -h |grep ceph-{{ item }} |awk '{print $1}'"
同上

2017-08-25 05:51 UTC, hackerain commented on roles/storage/tasks/del_osd_partition.yml
> +    register: ceph_osd_disk
当测试多个osd时，这个变量会被覆盖的，下面的逻辑就不正确了，这个情况需要考虑到

2017-08-25 09:31 UTC, closed without merging

2017-08-25 09:32 UTC, haoxiaoci commented
abandon